import { useState } from 'react'; import { Link } from '@tanstack/react-router'; import { Reveal } from '../../shared/components/Reveal';
import './homepage.css';
import './nutrition.css';
import './faq.css';

function PhonePreview() { return <div className="phone"><div className="phone-notch" /><div className="phone-top"><span>9:41</span><span>▮▮▮ ◒</span></div><h3>Hello, Alex <span>👋</span></h3><p>Today’s Progress</p><div className="phone-progress"><div className="calorie-ring"><strong>1720</strong><small>/2300 kcal</small></div><div className="macro-bars"><div><span>Protein <b>115/160g</b></span><i><em style={{ width: '72%' }} /></i></div><div><span>Carbs <b>180/250g</b></span><i><em style={{ width: '72%' }} /></i></div><div><span>Fat <b>55/70g</b></span><i><em style={{ width: '78%' }} /></i></div></div></div><div className="meal-heading"><b>Today’s Meals</b><span>See all</span></div>{[['Breakfast', 'Protein bowl', '420 kcal · 28g'], ['Lunch', 'Chicken avocado', '650 kcal · 48g'], ['Dinner', 'Salmon rice', '540 kcal · 38g']].map(([time, name, macros]) => <div className="phone-meal" key={time}><span>◉</span><div><small>{time}</small><b>{name}</b></div><small>{macros}</small></div>)}<div className="phone-nav"><span>⌂<small>Home</small></span><span>□<small>Recipes</small></span><strong>＋</strong><span>▥<small>Planner</small></span><span>♙<small>Profile</small></span></div></div> }

function FaqItem({ question, answer, isOpen, onOpen }: { question: string; answer: string; isOpen: boolean; onOpen: () => void }) { return <article className={`faq-item ${isOpen ? 'is-open' : ''}`}><button type="button" aria-expanded={isOpen} onClick={onOpen}>{question}</button>{isOpen && <p>{answer}</p>}</article>; }

function SiteFooter() { return <footer className="site-footer"><nav><a href="#features">About FitMeal</a><a href="#features">Recipes</a><a href="#how-it-works">Nutrition</a><Link to="/planner">Meal Planner</Link><Link to="/progress">Progress</Link></nav><div className="social-links"><a href="https://facebook.com" aria-label="Facebook">f</a><a href="https://instagram.com" aria-label="Instagram">◎</a><a href="https://x.com" aria-label="X">𝕏</a><a href="https://github.com" aria-label="GitHub">◉</a><a href="https://youtube.com" aria-label="YouTube">▶</a></div><p>© {new Date().getFullYear()} FitMeal. Eat well, plan simply, feel better.</p></footer>; }

export function HomePage() {
  const [openQuestion, setOpenQuestion] = useState<string | null>(null);
  const [showAllQuestions, setShowAllQuestions] = useState(false);
  const goals = [['↓', 'Lose weight', 'A modest calorie deficit helps you make steady progress while prioritising protein, fibre and satisfying meals.'], ['=', 'Maintain weight', 'Keep your energy stable with balanced meals that support your routine, training and everyday life.'], ['↑', 'Gain weight', 'Use a gentle calorie surplus and protein-rich meals to support healthy muscle and weight gain.']];
  const steps = [['01', 'Tell us your goal', 'Add your height, weight, activity level and whether you want to lose, maintain or gain weight.'], ['02', 'Get your meal targets', 'FitMeal calculates a daily calorie and macro starting point, then creates a balanced meal outline.'], ['03', 'Check in and adjust', 'Log your weight over time, notice the trend, and refresh your plan when your needs change.']];
  const faqs = [['How does FitMeal create my calorie target?', 'FitMeal uses your age, sex, height, weight, activity level and chosen goal to estimate daily energy needs. It then applies a modest adjustment for losing or gaining weight.'], ['Can FitMeal help me lose weight or gain weight?', 'Yes. Choose lose, maintain or gain when you set up your profile. FitMeal adjusts your daily calorie target and protein goal to suit that direction.'], ['What happens after I save my profile?', 'You can generate a daily meal plan with calorie and protein estimates, ask FitMeal AI general meal-planning questions, and log weight check-ins on the Progress page.'], ['Are calorie targets exact?', 'They are a practical starting estimate, not an exact prescription. Your needs can vary, so use your energy, hunger and progress over several weeks to guide adjustments.'], ['How often should I log my weight?', 'Many people find one or two check-ins per week useful. Focus on the longer trend instead of reacting to normal daily changes from hydration, food and routine.'], ['Can I update my goal or body details later?', 'Yes. Return to the profile section on the home page, update your details, and save again. Generate a fresh meal plan afterwards so its targets use your newest information.'], ['Can one meal be called healthy or unhealthy?', 'Usually, no. A balanced eating pattern matters more than one individual meal. FitMeal supports flexible, nourishing habits without labelling foods as good or bad.'], ['Is FitMeal AI a doctor or dietitian?', 'No. The assistant provides general planning and nutrition guidance only. It does not diagnose, prescribe or replace advice from a doctor or registered dietitian.'], ['Where does the nutrition data come from?', 'Your starting targets are calculated from established energy-estimation formulas. Meal information is designed for planning and education; check product labels for exact packaged-food values.']];
  return <>
    <section className="reference-hero"><Reveal className="hero-copy"><span className="eyebrow">Track. Eat. Achieve.</span><h1 className="text-balance">Healthier Eating<br />Starts with<br /><em>Every Meal</em></h1><p>FitMeal helps you understand nutrition, discover balanced recipes, plan meals and build eating habits that work in everyday life.</p><div className="hero-actions"><Link className="primary" to="/planner">Get Started Free</Link><a className="how-it-works" href="#how-it-works"><span>▶</span>How FitMeal works</a></div><div className="social-proof"><div><b>AB</b><b>CD</b><b>EF</b><b>GH</b></div><p><strong>Clear nutrition tools</strong> for everyday meals, personal goals and informed choices.</p></div></Reveal><Reveal className="hero-visual" delay={170}><div className="food-photo" aria-label="Healthy chicken, avocado and tomato bowl" /><PhonePreview /></Reveal></section>
    <section id="features" className="feature-cards">{[['♨', 'View Progress', 'See your habits and stay motivated.'], ['▤', 'Healthy Recipes', 'Simple food ideas for every day.'], ['▥', 'Meal Planning', 'Build a plan around your goals.'], ['▥', 'Food Database', 'Understand what is on your plate.']].map(([icon, title, text], index) => <Reveal key={title} delay={index * 100}><article><span>{icon}</span><h3>{title}</h3><p>{text}</p></article></Reveal>)}</section>
    <Reveal className="nutrition-intro"><div><span className="eyebrow">Built around you</span><h2>Not another one-size-fits-all diet.</h2></div><p>FitMeal estimates your daily energy needs from your weight, height, age, activity level and goal. It then turns those numbers into a simple daily plan you can actually follow.</p></Reveal>
    <section className="goal-grid">{goals.map(([symbol, title, text], index) => <Reveal key={title} delay={index * 110}><article><span>{symbol}</span><h3>{title}</h3><p>{text}</p></article></Reveal>)}</section>
    <section id="how-it-works" className="steps"><Reveal><span className="eyebrow">A simple routine</span><h2>Know what to do next.</h2></Reveal><div>{steps.map(([number, title, text], index) => <Reveal key={number} delay={index * 140}><article><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></article></Reveal>)}</div></section>
    <Reveal className="macro-note"><div><span className="eyebrow">Nutrition, made clear</span><h2>Calories give you energy.<br /><em>Macros help you use it well.</em></h2></div><div className="macro-explainer"><p><strong>Protein</strong> supports muscles and helps meals feel satisfying.</p><p><strong>Carbohydrates</strong> fuel your brain, training and daily movement.</p><p><strong>Fats</strong> support hormones, nutrient absorption and flavour.</p><small>Targets are helpful starting points, not medical advice. If you have a health condition or special dietary needs, speak with a qualified professional.</small></div></Reveal>
    <Reveal className="nutrition-basics"><div><span className="eyebrow">Nutrition basics</span><h2>A healthy diet is more than counting calories.</h2><p>The World Health Organization describes four foundations of healthy eating: adequacy, balance, moderation and diversity. Individual needs still vary with age, lifestyle, culture and health.</p><div className="guidance-links"><a href="https://www.who.int/news-room/fact-sheets/detail/healthy-diet" target="_blank" rel="noreferrer">WHO guidance ↗</a><a href="https://www.dge.de/gesunde-ernaehrung/gut-essen-und-trinken/die-dge-empfehlungen/" target="_blank" rel="noreferrer">DGE recommendations ↗</a></div></div><div className="nutrition-tips">{[['🥕', 'Eat varied and colourful', 'Build meals around vegetables, fruit, pulses, whole grains, nuts and other nutrient-rich foods.'], ['💧', 'Choose water first', 'Water and unsweetened drinks are practical everyday choices.'], ['🌾', 'Prefer fibre-rich foods', 'Whole grains, vegetables, fruit and pulses support fibre intake and fullness.'], ['⚖️', 'Think in patterns', 'One food does not define health. Overall balance, portions and regular habits matter.']].map(([icon, title, text]) => <article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></Reveal>
    <Reveal className="mobile-soon"><span className="coming-soon">Coming soon</span><h2>FitMeal will also be available as a mobile app</h2><p>We are planning a simple FitMeal app for your phone. It will give you quick access to recipes, nutrition tracking and your personal meal plan while you are on the go.</p><div className="mobile-steps">{[['1', 'Download the app', 'Get FitMeal from your phone’s app store when it becomes available.'], ['2', 'Use the same account', 'Log in with your existing FitMeal account—no new profile needed.'], ['3', 'Continue anywhere', 'Your planned meals, nutrition entries and progress will stay connected.']].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div><small>The website remains fully usable. The mobile app is a planned additional option and is not available for download yet.</small></Reveal>
    <section className="faq-section"><Reveal><span className="eyebrow">Frequently asked</span><h2>Frequently asked questions</h2></Reveal><Reveal className="faq-list" delay={100}>{faqs.slice(0, showAllQuestions ? faqs.length : 5).map(([question, answer]) => <FaqItem key={question} question={question} answer={answer} isOpen={openQuestion === question} onOpen={() => setOpenQuestion(current => current === question ? null : question)} />)}<button type="button" className="show-more" onClick={() => { setShowAllQuestions(current => !current); setOpenQuestion(null); }}>{showAllQuestions ? 'Show fewer questions' : `See all questions (${faqs.length})`}</button></Reveal></section>
    <Reveal className="final-cta"><h2>Ready to get started?</h2><p>Start exploring healthy meal ideas today.</p><Link className="primary" to="/planner">View meal planner</Link></Reveal>
    <SiteFooter />
  </>;
}
